baseURL = 'https://nannannanhe.github.io/blog/'
languageCode = 'zh-TW'
timeZone = "Asia/Tokyo"
title = 'nannannanhe open notes'
description = "Personal open notes by nannannanhe. Learning in public."
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true

[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 30

[services]
[services.googleAnalytics]
id = 'G-EFWFTFTSVG'

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
env = 'production'
title = 'nannannanhe'
description = "Personal open notes by nannannanhe. Learning in public."
keywords = ['blog', 'open notes', 'kaggle', 'hugo', 'aws']
author = 'nannannanhe'
defaultTheme = 'light'
ShowBreadCrumbs = true
mainSections = ["posts"]

# home-info mode
[params.homeInfoParams]
title = 'Personal Open Notes'
content = """
Learning in public.<br>
Mainly in Traditional Chinese.
"""

[markup.goldmark.renderer]
unsafe = true
